name: app-vue
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data
    replicas: 1
    ports:
      - 8080:8080
    resources:
      cpu: 300m
      memory: 500Mi