name: app-vue
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /data
    replicas: 1
    ports:
      - 8080:8080
    resources:
      cpu: 300m
      memory: 500Mi
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3